Add APIError
MiaoSiLa/go-umeng pull request #2
Opened 2018-10-22 08:57 UTC by MyYellowBlanket

[友盟的错误可以被统一返回成 error](https://github.com/MiaoSiLa/mpush/issues/7)

2018-10-22 18:21 UTC, tengattack requested changes
**lint**: 5 problem(s) found.

2018-10-22 18:21 UTC, tengattack commented on http_client.go
> +	respHttp, err := client.Do(req)
`golint` 328:2 var respHttp should be respHTTP

2018-10-22 18:21 UTC, tengattack commented on http_client_test.go
> +	"github.com/stretchr/testify/assert"
`goreturns` 5:0 
```diff
-	"github.com/stretchr/testify/assert"
```

2018-10-22 18:24 UTC, tengattack requested changes
**lint**: 5 problem(s) found.

2018-10-22 18:24 UTC, tengattack commented on http_client.go
> +	respHttp, err := client.Do(req)
`golint` 328:2 var respHttp should be respHTTP

2018-10-22 18:24 UTC, tengattack commented on http_client_test.go
> +	"github.com/stretchr/testify/assert"
`goreturns` 5:0 
```diff
-	"github.com/stretchr/testify/assert"
```

2018-10-22 18:56 UTC, tengattack commented on http_client.go
> +	respHttp, err := client.Do(req)
这里为啥要改名呢

2018-10-23 20:19 UTC, tengattack commented on http_client.go
> +// Result type can store the "data" section of umeng JSON respond
这里应该考虑使用 `response` 而不是 `respond`

2018-10-23 20:20 UTC, tengattack commented on http_client.go
> +type respond struct {
APIResponse 比较合适感觉

2018-10-24 04:19 UTC, MyYellowBlanket commented on http_client.go
> +// Result type can store the "data" section of umeng JSON respond
这个类型是想在 package umeng 内部自己用的，那就改成小写的 response 吧

2018-10-25 08:54 UTC, tengattack commented on http_client.go
> +			err = newAPIError("unexpected response content")
这里可以加个 http 状态？

2018-10-25 08:54 UTC, tengattack commented on http_client.go
> +// Result type can store the "data" section of umeng JSON respond
好的

2018-10-25 09:33 UTC, tengattack requested changes
**lint**: 1 problem(s) found.

2018-10-25 09:33 UTC, tengattack commented on http_client.go
> +		} else {
`golint` 344:10 if block ends with a return statement, so drop this else and outdent its block

2018-10-25 09:48 UTC, merged